# @package emission

_target_: "dcase24t6.callbacks.emissions.CustomEmissionTracker"

save_dir: ${save_dir}
emissions_fname: "emissions/{task}_emissions.yaml"
country_iso_code: null
offline: true
disabled: true

experiment_name: ${save_name}
