# @package emission

_target_: "dcase24t6.callbacks.emissions.CustomEmissionTracker"

save_dir: ${save_dir}
emissions_fname: "{task}_emissions.yaml"
country_iso_code: ???
offline: true
disabled: false

experiment_name: ${save_name}
