# @package _global_

trainer:
  max_epochs: 3
  limit_predict_batches: 2
  limit_test_batches: 2
  limit_train_batches: 2
  limit_val_batches: 2
  accumulate_grad_batches: 1

datamodule:
  batch_size: 4
