# @package _global_

trainer:
  max_epochs: 10
  limit_predict_batches: 10
  limit_test_batches: 10
  limit_train_batches: 10
  limit_val_batches: 10
  accumulate_grad_batches: 1

datamodule:
  batch_size: 16
