# @package _global_

trainer:
  max_epochs: 400
  limit_predict_batches: null
  limit_test_batches: null
  limit_train_batches: null
  limit_val_batches: null
  accumulate_grad_batches: 8
  log_every_n_steps: 5

datamodule:
  batch_size: 64

save_name: "${hydra:job.name}-${datetime}-dbg4"
