# @package ckpt

_target_: "aac.callbacks.custom_ckpt.CustomModelCheckpoint"

dirpath: "${hydra:sweep.dir}/${hydra:sweep.subdir}/checkpoints"
save_last: false
save_top_k: 1
monitor: "val/loss"
mode: "min"
verbose: ${verbose}
filename: "{epoch:03d}-{step:06d}-mode_${ckpts.0.mode}-{${ckpts.0.monitor}:.4f}"  # default: "{epoch}-{step}"
