# @package trainer

_target_: "lightning.pytorch.trainer.Trainer"

accelerator: "gpu"
accumulate_grad_batches: 1
benchmark: false
detect_anomaly: false
deterministic: false
devices: 1
enable_checkpointing: true
enable_model_summary: false
fast_dev_run: false
gradient_clip_algorithm: "norm"
gradient_clip_val: 1
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 5
max_epochs: 400
max_steps: -1
num_nodes: 1
num_sanity_val_steps: 0
precision: 32
reload_dataloaders_every_n_epochs: 0
val_check_interval: null
