# @package _global_

defaults:
  - pre_process: cnext
  - path: local
  - hydra: custom
  - _self_

# --- Common args
datetime: ${now:%Y.%m.%d-%H.%M.%S}  # str
save_name: "${hydra:job.name}-${datetime}"
seed: 42  # int | null
verbose: 1  # int (0 = WARNING, 1 = INFO, 2 = DEBUG)


# --- Prepare args
subsets: ["dev", "val", "eval", "dcase_aac_test", "dcase_aac_analysis"]
force: false

hdf_pattern: "{dataset}_{subset}_${hydra:runtime.choices.pre_process}.hdf"  # str
overwrite: false  # bool
batch_size: 32  # int
num_workers: "auto"  # int | "auto"
